
import { DocPageLayout } from "@/components/doc-page-layout";
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Terms of Service | VisionHub AI',
  description: 'Read the terms of service for using the VisionHub AI platform.',
};

const sections = [
    { id: 'acceptance', title: '1. Acceptance of Terms' },
    { id: 'user-accounts', title: '2. User Accounts' },
    { id: 'content-ownership', title: '3. Content Ownership and Licensing' },
    { id: 'refund-policy', title: '4. Refund Policy' },
];

export default function TermsPage() {
    return (
        <DocPageLayout
            title="Terms of Service"
            description="Last updated: "
            sections={sections}
        >
            <section id="acceptance">
                <h2>1. Acceptance of Terms</h2>
                <p>By accessing or using the VisionHub AI platform ("Service"), you agree to be bound by these Terms of Service ("Terms"). If you disagree with any part of the terms, then you may not access the Service. This agreement applies to all visitors, users, and others who wish to access or use the Service.</p>
                <p>We reserve the right to update or change these Terms at any time by posting the most current version of the Terms on the Site with a new "Last Updated" date. All such changes will be effective immediately upon posting. Your continued use of the Service after any such change constitutes your acceptance of the new Terms.</p>
            </section>
            
            <section id="user-accounts">
                <h2>2. User Accounts</h2>
                <p>To access certain features of the Service, you must register for an account. When you register for an account, you may be required to provide us with some information about yourself, such as your email address or other contact information. You agree that the information you provide to us is accurate and that you will keep it accurate and up-to-date at all times.</p>
                <p>You are solely responsible for maintaining the confidentiality of your account and password, and you accept responsibility for all activities that occur under your account. If you have reason to believe that your account is no longer secure, then you must immediately notify us at support@visionhub.ai.</p>
            </section>

            <section id="content-ownership">
                <h2>3. Content Ownership and Licensing</h2>
                <p>For the purposes of these Terms, "Content" means any images, text, or other materials generated, provided, or otherwise made available through the Service.</p>
                <p><strong>Your Content:</strong> You retain all ownership rights to the prompts you submit to the Service. </p>
                <p><strong>Generated Content:</strong> Subject to your compliance with these Terms, VisionHub AI grants you a perpetual, worldwide, non-exclusive, royalty-free license to use, reproduce, display, and distribute the images generated by the Service for any lawful purpose, including commercial use. However, you acknowledge that the generated images are created by an AI model and may be similar or identical to images generated for other users. We make no claims about the copyright status of generated images, and it is your responsibility to ensure your use of the content complies with all applicable laws.</p>
                <p>You are solely responsible for the prompts you provide and the subsequent use of any generated content. You agree not to create any content that is illegal, defamatory, obscene, or infringes on the rights of any third party, including copyright, trademark, privacy, or other personal or proprietary rights.</p>
            </section>
            
            <section id="refund-policy">
                <h2>4. Refund Policy</h2>
                <p>Our goal is to provide a satisfactory experience for all our users. Our policy for refunds on credit packages is as follows:</p>
                <ul className="list-disc list-inside space-y-2 my-4">
                    <li>All purchases of credit packages are considered final.</li>
                    <li><strong>Refunds will not be provided for any credit package purchase valued under 500 credits.</strong></li>
                    <li>For larger packages or in exceptional circumstances, you may contact our support team to discuss your situation. Refund eligibility will be determined on a case-by-case basis at our sole discretion.</li>
                    <li>To request a refund review, please contact us via the contact form or email us at prabud0401@gmail.com with your transaction details and reason for the request.</li>
                </ul>
            </section>
        </DocPageLayout>
    );
}
